my_string = input("Input text: ")
print("Нou have entered the text:", my_string)
str_length = len(my_string)
print("String length:", str_length)

print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ", ""))
print(my_string[0])
print(my_string[-1])